#ifndef RESOURCE_H
#define RESOURCE_H

// Menu bar
#define ID_MENU_VIEW_LOG 201
#define ID_MENU_RESCAN_LIBRARIES 202
#define ID_MENU_EXIT 203
#define ID_MENU_ABOUT 204
#define ID_MENU_COLLECT_BACKUPS 205
#define ID_MENU_EXPORT_LIBRARY_LIST 206

// Log viewer edit
#define IDD_LOGVIEW_BOX 301
#define IDC_LOGVIEW_EDIT 302

// About dialog
#define IDD_ABOUT_BOX 401
#define IDC_VER_LABEL 402
#define IDC_BUILD_LABEL 403
#define IDC_REPO_LINK 404
#define IDC_CHECK_UPDATES_BUTTON 405

// Remove Selected dialog
#define IDD_REMOVE_SELECTED_BOX 501
#define IDC_REMOVE_SELECTED_NAME 502
#define IDC_REMOVE_SELECTED_CONTENT_DIR 503
#define IDC_REMOVE_SELECTED_INFO_TEXT 504
#define IDC_REMOVE_SELECTED_BACKUP_CHECK 505
#define IDC_REMOVE_SELECTED_CONTENT_DIR_CHECK 506
#define ID_REMOVE_SELECTED_REMOVE 507
#define ID_REMOVE_SELECTED_CANCEL 508
#define IDC_REMOVE_SELECTED_WARNING_TEXT 509

// Progress dialog
#define IDD_PROGRESS_BOX 601
#define IDC_PROGRESS_BAR 602
#define IDC_PROGRESS_TEXT 602

#define IDD_RELOCATE_SELECTED_BOX 701
#define IDC_RELOCATE_SELECTED_NAME 702
#define IDC_RELOCATE_SELECTED_CONTENT_DIR 703
#define IDC_RELOCATE_SELECTED_PATH_EDIT 704
#define IDC_RELOCATE_SELECTED_BROWSE_BUTTON 705
#define ID_RELOCATE_SELECTED_RELOCATE 706
#define ID_RELOCATE_SELECTED_CANCEL 707

// App icon
#define IDI_APPICON 1001

#endif
