#ifndef RESOURCE_H
#define RESOURCE_H

// Main window
#define IDC_LISTBOX 101
#define IDC_REMOVE_BUTTON 102
#define IDC_REMOVE_ALL_BUTTON 103
#define IDC_CHECKBOX_BACKUP 104
#define IDC_CHECKBOX_REMOVE_LIB_FOLDER 105
#define IDC_RELOCATE_BUTTON 106
#define IDC_PROGRESS_BAR 107
#define IDC_PROGRESS_TEXT 108
#define IDC_PROGRESS_PANEL 109
#define IDC_PROGRESS_CANCEL_BUTTON 110

// Menu bar
#define ID_MENU_VIEW_LOG 201
#define ID_MENU_RELOAD_LIBRARIES 202
#define ID_MENU_EXIT 203
#define ID_MENU_CHECK_UPDATES 204
#define ID_MENU_ABOUT 205
#define ID_MENU_COLLECT_BACKUPS 206

// Log viewer edit
#define IDC_LOGVIEW_EDIT 301

// About dialog
#define IDD_ABOUTBOX 401
#define IDC_VER_LABEL 402
#define IDC_BUILD_LABEL 403
#define IDC_REPO_LINK 404

// Remove dialog
#define IDD_REMOVE_LIBRARYBOX 501
#define IDC_REMOVE_LIBRARY_NAME 502
#define IDC_REMOVE_INFO_TEXT 503
#define IDC_REMOVE_BACKUP_CHECK 504
#define IDC_REMOVE_FOLDER_CHECK 505
#define IDC_REMOVE_LIBRARY_CONTENT_DIR 506
#define IDREMOVE 507
#define IDCANCEL_REMOVE 508

// Removal All dialog
#define IDD_BATCH_REMOVEBOX 601
#define IDC_BATCH_LIBRARY_LIST 602
#define IDC_BATCH_SELECT_ALL 603
#define IDC_BATCH_DESELECT_ALL 604
#define IDC_BATCH_BACKUP_CHECK 605
#define IDC_BATCH_FOLDER_CHECK 606
#define IDC_BATCH_COUNT_LABEL 607
#define IDREMOVE_BATCH 608
#define IDCANCEL_BATCH 609

// Relocate dialog
#define IDD_RELOCATE_LIBRARYBOX 701
#define IDC_LIB_NAME_LABEL 702
#define IDC_CONTENT_DIR_LABEL 703
#define IDRELOCATE_RELOCATE 704
#define IDCANCEL_RELOCATE 705
#define IDC_RELOCATE_PATH_EDIT 706
#define IDC_RELOCATE_BROWSE_BTN 707

// App icon
#define IDI_APPICON 1001

#endif
